"""Scoring rules, the paired bootstrap, Diebold-Mariano and FDR control.

The load-bearing test here is :func:`test_byte_identity_with_wc2026`. The ported scoring functions
exist so that a number computed in this project is directly comparable with one computed in the
WC2026 project; if they drift, every cross-reference in NOTES.md silently becomes wrong. The
fixture was generated by running that project's own code (see
``tests/fixtures/make_wc2026_golden.py``).
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from plmodel.eval import metrics

FIXTURE = Path(__file__).resolve().parent / "fixtures" / "wc2026_metrics_golden.json"


@pytest.fixture(scope="module")
def golden() -> dict:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def case(golden: dict) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    inp = golden["inputs"]
    return (
        np.asarray(inp["probs_a"], dtype=float),
        np.asarray(inp["probs_b"], dtype=float),
        np.asarray(inp["outcomes"], dtype=int),
    )


# --- the verbatim port ---------------------------------------------------------------------

def test_byte_identity_with_wc2026(golden: dict, case) -> None:
    """Every ported function must reproduce the WC2026 output exactly, not approximately."""
    probs_a, probs_b, outcomes = case
    want = golden["expected"]
    uniform = metrics.uniform_baseline(len(outcomes))

    assert metrics.rps(probs_a, outcomes).tolist() == want["rps_a"]
    assert metrics.rps(probs_b, outcomes).tolist() == want["rps_b"]
    assert metrics.log_loss(probs_a, outcomes).tolist() == want["log_loss_a"]
    assert metrics.brier(probs_a, outcomes).tolist() == want["brier_a"]
    assert metrics.mean_rps(probs_a, outcomes) == want["mean_rps_a"]
    assert metrics.mean_rps(probs_b, outcomes) == want["mean_rps_b"]
    assert metrics.mean_log_loss(probs_a, outcomes) == want["mean_log_loss_a"]
    assert metrics.mean_brier(probs_a, outcomes) == want["mean_brier_a"]
    assert metrics.mean_rps(uniform, outcomes) == want["mean_rps_uniform"]
    assert metrics.summary(probs_a, outcomes) == want["summary_a"]
    assert metrics.skill(want["mean_rps_a"], want["mean_rps_uniform"]) == want["skill_a"]
    assert metrics.outcome_from_scores(
        np.array([3, 1, 0, 2]), np.array([1, 1, 2, 5])
    ).tolist() == want["outcome_from_scores"]


def test_paired_delta_byte_identity(golden: dict, case) -> None:
    """The bootstrap must reproduce exactly — same RNG stream, same resamples, same CI."""
    probs_a, probs_b, outcomes = case
    assert metrics.paired_delta(probs_a, probs_b, outcomes) == golden["expected"]["paired_delta_ab"]
    assert metrics.paired_delta(
        probs_a, probs_b, outcomes, n_boot=2000, seed=7
    ) == golden["expected"]["paired_delta_ab_seed7_boot2000"]


def test_uniform_per_outcome_scores() -> None:
    """Uniform is not flat across outcomes: 5/18 for a home or away win, 1/9 for a draw.

    Because C = (1/3, 2/3), a draw is the outcome the uniform forecast is *least* wrong about.
    The oft-quoted 0.2222 is the expectation over a balanced outcome mix, not a per-match value —
    see :func:`test_uniform_expectation_is_two_ninths`.
    """
    uniform = metrics.uniform_baseline(3)
    per_match = metrics.rps(uniform, np.array([0, 1, 2]))
    assert per_match[0] == pytest.approx(5 / 18)
    assert per_match[1] == pytest.approx(1 / 9)
    assert per_match[2] == pytest.approx(5 / 18)


def test_uniform_expectation_is_two_ninths() -> None:
    """The 0.2222 sanity floor: uniform against a balanced outcome mix."""
    out = np.array([0, 1, 2])
    assert metrics.mean_rps(metrics.uniform_baseline(len(out)), out) == pytest.approx(2 / 9)


def test_perfect_forecast_scores_zero() -> None:
    probs = np.array([[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]])
    assert metrics.mean_rps(probs, np.array([0, 1, 2])) == 0.0


def test_rps_respects_ordinality() -> None:
    """The point of RPS over Brier: being wrong by two classes must cost more than by one."""
    outcomes = np.array([0])
    near = metrics.mean_rps(np.array([[0.0, 1.0, 0.0]]), outcomes)   # predicted draw
    far = metrics.mean_rps(np.array([[0.0, 0.0, 1.0]]), outcomes)    # predicted away
    assert far > near


def test_skill_is_zero_against_itself() -> None:
    assert metrics.skill(0.22, 0.22) == 0.0


def test_shape_violations_raise() -> None:
    with pytest.raises(ValueError, match=r"probs must be \(N, 3\)"):
        metrics.rps(np.zeros((4, 2)), np.zeros(4, dtype=int))
    with pytest.raises(ValueError, match="length mismatch"):
        metrics.rps(np.zeros((4, 3)), np.zeros(3, dtype=int))
    # Mismatched arms are caught by the per-arm length check before the shape comparison; the
    # `same shape` branch in paired_delta is unreachable given _check's own contract, and is kept
    # only because this is a verbatim port.
    with pytest.raises(ValueError, match="length mismatch"):
        metrics.paired_delta(np.zeros((4, 3)), np.zeros((5, 3)), np.zeros(4, dtype=int))


def test_paired_delta_call_sites_pass_seed_and_n_boot() -> None:
    """The companion guard for the magic-number exemption on eval/metrics.py.

    ``paired_delta`` keeps its WC2026 defaults so the port stays verbatim, which means nothing
    stops a call site from silently inheriting them instead of reading config. This asserts none
    does.
    """
    import ast

    src_root = Path(__file__).resolve().parents[1] / "src" / "plmodel"
    offenders: list[str] = []
    for path in src_root.rglob("*.py"):
        if path.name == "metrics.py":
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            fn = node.func
            name = fn.attr if isinstance(fn, ast.Attribute) else getattr(fn, "id", None)
            if name != "paired_delta":
                continue
            passed = {kw.arg for kw in node.keywords}
            missing = {"n_boot", "seed"} - passed
            if missing:
                offenders.append(f"{path.name}:{node.lineno} does not pass {sorted(missing)}")
    assert not offenders, "paired_delta must be called with explicit config values:\n  " + \
        "\n  ".join(offenders)


# --- Diebold-Mariano ---------------------------------------------------------------------------

def test_dm_and_bootstrap_agree_in_sign(case) -> None:
    """Two tests with different assumptions pointing the same way is the robustness signal."""
    probs_a, probs_b, outcomes = case
    delta = metrics.paired_delta(probs_a, probs_b, outcomes, n_boot=2000, seed=1)
    dm = metrics.diebold_mariano(
        metrics.rps(probs_a, outcomes), metrics.rps(probs_b, outcomes)
    )
    assert np.sign(dm["dm_hln"]) == np.sign(delta["delta_rps"])
    assert dm["mean_diff"] == pytest.approx(delta["delta_rps"])


def test_dm_sign_convention_favours_a() -> None:
    """Negative favours A, matching paired_delta — a sign flip here would invert every verdict."""
    rng = np.random.default_rng(0)
    loss_a = rng.normal(0.20, 0.05, size=400)
    loss_b = loss_a + rng.normal(0.01, 0.01, size=400)  # B is reliably worse
    dm = metrics.diebold_mariano(loss_a, loss_b)
    assert dm["dm_hln"] < 0 and dm["p_value"] < 0.05


def test_dm_identical_forecasts_are_a_clean_null() -> None:
    loss = np.linspace(0.1, 0.3, 50)
    dm = metrics.diebold_mariano(loss, loss.copy())
    assert dm["dm_stat"] == 0.0 and dm["p_value"] == 1.0


def test_hln_correction_shrinks_the_statistic() -> None:
    """The whole point of the correction: raw DM is oversized in small samples."""
    rng = np.random.default_rng(3)
    loss_a = rng.normal(0.2, 0.05, size=40)
    loss_b = loss_a + 0.01
    dm = metrics.diebold_mariano(loss_a, loss_b)
    assert abs(dm["dm_hln"]) < abs(dm["dm_stat"])


def test_zero_lag_variance_is_the_sample_variance() -> None:
    d = np.array([0.1, -0.2, 0.3, 0.05, -0.15])
    assert metrics._long_run_variance(d, 0) == pytest.approx(d.var())


def test_hac_widens_the_error_under_positive_autocorrelation() -> None:
    """Per-match RPS differences are serially correlated; ignoring it overstates significance."""
    rng = np.random.default_rng(5)
    noise = rng.normal(0, 1, size=600)
    d = noise.copy()
    for i in range(1, len(d)):
        d[i] += 0.7 * d[i - 1]  # AR(1), strongly positively autocorrelated
    assert metrics._long_run_variance(d, 12) > metrics._long_run_variance(d, 0)


def test_newey_west_lag_grows_with_sample_size() -> None:
    assert metrics.newey_west_lag(100) == 4
    assert metrics.newey_west_lag(3800) >= metrics.newey_west_lag(380)


def test_dm_input_validation() -> None:
    with pytest.raises(ValueError, match="same shape"):
        metrics.diebold_mariano(np.zeros(5), np.zeros(6))
    with pytest.raises(ValueError, match="1-D"):
        metrics.diebold_mariano(np.zeros((5, 2)), np.zeros((5, 2)))
    with pytest.raises(ValueError, match="at least two"):
        metrics.diebold_mariano(np.zeros(1), np.zeros(1))
    with pytest.raises(ValueError, match="out of range"):
        metrics.diebold_mariano(np.zeros(5), np.ones(5), lag=5)


# --- Benjamini-Hochberg ------------------------------------------------------------------------

def test_bh_worked_example() -> None:
    """Standard step-up example: four of five rejected at alpha = 0.05."""
    out = metrics.benjamini_hochberg([0.005, 0.011, 0.02, 0.04, 0.13], alpha=0.05)
    assert out["n_rejected"] == 4
    assert out["rejected"] == [True, True, True, True, False]
    assert out["threshold"] == pytest.approx(0.04)
    assert out["p_adjusted"][0] == pytest.approx(0.025)


def test_bh_preserves_names(case) -> None:
    out = metrics.benjamini_hochberg({"gbm": 0.001, "rest": 0.30, "xg": 0.04}, alpha=0.05)
    assert set(out["rejected"]) == {"gbm", "rest", "xg"}
    assert out["rejected"]["gbm"] is True and out["rejected"]["rest"] is False


def test_bh_adjusted_p_values_are_monotone() -> None:
    rng = np.random.default_rng(11)
    p = np.sort(rng.uniform(0, 1, size=40))
    adjusted = metrics.benjamini_hochberg(p, alpha=0.1)["p_adjusted"]
    assert all(a <= b + 1e-12 for a, b in zip(adjusted, adjusted[1:]))


def test_bh_rejects_nothing_when_everything_is_null() -> None:
    """25 arms of pure noise must not yield a discovery — the reason FDR control is here."""
    rng = np.random.default_rng(12)
    p = rng.uniform(0, 1, size=25)
    assert metrics.benjamini_hochberg(p, alpha=0.05)["n_rejected"] <= 1


def test_bh_is_less_conservative_than_bonferroni() -> None:
    p = [0.001, 0.008, 0.02, 0.2, 0.5]
    bh = metrics.benjamini_hochberg(p, alpha=0.05)["n_rejected"]
    bonferroni = sum(x <= 0.05 / len(p) for x in p)
    assert bh >= bonferroni


def test_bh_validation() -> None:
    with pytest.raises(ValueError, match="alpha must be"):
        metrics.benjamini_hochberg([0.1], alpha=0.0)
    with pytest.raises(ValueError, match="non-empty"):
        metrics.benjamini_hochberg([], alpha=0.05)
    with pytest.raises(ValueError, match=r"p-values must lie"):
        metrics.benjamini_hochberg([0.5, 1.5], alpha=0.05)


# --- clustered bootstrap -----------------------------------------------------------------------

def test_clustering_widens_the_interval_when_the_shock_is_shared() -> None:
    """The whole reason it exists: rows inside a season are not twenty observations."""
    rng = np.random.default_rng(0)
    groups = np.repeat(np.arange(10), 20)
    shared = rng.normal(0.0, 1.0, 10)[groups]
    a, b = shared + rng.normal(0.0, 0.1, 200), np.zeros(200)
    naive = metrics.paired_delta_losses(a, b, n_boot=2000, seed=1)
    clustered = metrics.paired_delta_clustered(a, b, groups, n_boot=2000, seed=1)
    assert clustered["ci_high"] - clustered["ci_low"] > 3 * (naive["ci_high"] - naive["ci_low"])
    assert clustered["delta"] == pytest.approx(naive["delta"])
    assert clustered["n"] == 200 and clustered["n_groups"] == 10


def test_one_row_per_group_is_the_ordinary_bootstrap() -> None:
    """With no clustering to do, it must not quietly become a different estimator."""
    rng = np.random.default_rng(2)
    a, b = rng.normal(size=60), rng.normal(size=60)
    groups = np.arange(60)
    clustered = metrics.paired_delta_clustered(a, b, groups, n_boot=4000, seed=7)
    plain = metrics.paired_delta_losses(a, b, n_boot=4000, seed=7)
    assert clustered["delta"] == pytest.approx(plain["delta"])
    assert clustered["ci_low"] == pytest.approx(plain["ci_low"], abs=0.05)
    assert clustered["ci_high"] == pytest.approx(plain["ci_high"], abs=0.05)


def test_the_sign_convention_matches_its_siblings() -> None:
    groups = np.repeat(np.arange(5), 4)
    better, worse = np.full(20, 0.1), np.full(20, 0.3)
    got = metrics.paired_delta_clustered(better, worse, groups, n_boot=500, seed=0)
    assert got["delta"] < 0 and got["p_a_better"] == 1.0


def test_clustered_bootstrap_validation() -> None:
    groups = np.arange(4)
    with pytest.raises(ValueError, match="matching 1-D arrays"):
        metrics.paired_delta_clustered(np.zeros(4), np.zeros(5), groups, n_boot=10, seed=0)
    with pytest.raises(ValueError, match="empty sample"):
        metrics.paired_delta_clustered(np.zeros(0), np.zeros(0), np.zeros(0), n_boot=10, seed=0)


# --- a declared family larger than the tests supplied ---------------------------------------------

def test_a_declared_family_leaves_the_default_path_untouched() -> None:
    """The load-bearing one: passing family_size=None must change nothing.

    Every FDR number in the ledger was computed on the default path. If that moved, none of them
    would be reproducible, and the correction would be silently different from the one recorded.
    """
    p = [0.005, 0.011, 0.02, 0.04, 0.13]
    assert metrics.benjamini_hochberg(p, alpha=0.05) == metrics.benjamini_hochberg(
        p, alpha=0.05, family_size=None
    )
    assert metrics.benjamini_hochberg(p, alpha=0.05) == metrics.benjamini_hochberg(
        p, alpha=0.05, family_size=len(p)
    )


def test_a_larger_declared_family_raises_the_bar() -> None:
    """One arm scored alone, but pre-registered as one of three serial re-scorings.

    At m=1 the threshold is alpha; declaring a family of three makes it alpha/3, which is the
    number NOTES.md pre-committed for dc-gas before any of it was measured.
    """
    alone = metrics.benjamini_hochberg({"dc-gas": 0.03}, alpha=0.05)
    assert alone["rejected"]["dc-gas"] is True, "0.03 clears an uncorrected 0.05"

    declared = metrics.benjamini_hochberg({"dc-gas": 0.03}, alpha=0.05, family_size=3)
    assert declared["rejected"]["dc-gas"] is False, "0.03 does not clear 0.05/3"
    assert declared["p_adjusted"]["dc-gas"] == pytest.approx(0.09)
    assert declared["family_size"] == 3
    # n_tests still counts what was actually scored; the family is the wider claim.
    assert declared["n_tests"] == 1


def test_the_declared_family_only_ever_tightens() -> None:
    """A family smaller than the tests run would loosen the correction.

    Refused outright rather than clamped: a knob that can loosen a multiplicity correction is a
    knob for buying an acceptance, which is what the pre-commitments exist to prevent.
    """
    with pytest.raises(ValueError, match="smaller than"):
        metrics.benjamini_hochberg([0.01, 0.02, 0.03], alpha=0.05, family_size=2)


def test_the_declared_family_shifts_the_boundary_exactly() -> None:
    """alpha/N is the threshold for the smallest p-value, checked either side of it."""
    for family, boundary in ((1, 0.05), (3, 0.05 / 3), (4, 0.05 / 4)):
        just_under = metrics.benjamini_hochberg(
            {"a": boundary * 0.99}, alpha=0.05, family_size=family
        )
        just_over = metrics.benjamini_hochberg(
            {"a": boundary * 1.01}, alpha=0.05, family_size=family
        )
        assert just_under["rejected"]["a"] is True, f"family {family}"
        assert just_over["rejected"]["a"] is False, f"family {family}"
